export const WeatherCode = {
    0: 'Clear Sky',
    1: 'Mainly Clear',
    2: 'Partly Cloudy',
    3: 'Overcast',
    45: 'Fog',
    48: 'Depositing rime fog',
    51: 'Drizzle: light',
    53: 'Drizzle: moderate',
    55: 'Drizzle: dense intensity',
    56: 'Freezing Drizzle: Light',
    57: 'Freezing Drizzle: Dense Intensity',
    61: 'Rain: Slight',
    63: 'Rain: Moderate',
    65: 'Rain: Heavy intensity',
    66: 'Freezing Rain: Light',
    67: 'Freezing Rain: Heavy intensity',
    71: 'Snow fall: Slight',
    73: 'Snow fall: Moderate',
    75: 'Snow fall: Heavy intensity',
    77: 'Snow grains',
    80: 'Rain Showers: Slight',
    81: 'Rain Showers: Moderate',
    82: 'Rain Showers: Violent',
    85: 'Snow Showers: Slight',
    86: 'Snow Showers: Heavy',
    95: 'Thunderstorm: Slight or moderate',
    96: 'Thunderstorm with Slight',
    99: 'Thunderstorm with Heavy hail',
} as const;
type WeatherCode = typeof WeatherCode[keyof typeof WeatherCode];